version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
  build:
    commands:
      - echo Build started on `date`
      - echo Hello
  post_build:
    commands:
      - aws s3 cp s3://gitcodebuild/gitcodebuild.sh .
      - gitcodebuild.sh
  
