version: 0.2

CMD=$@
XYZ=$(expect -c "
spawn ssh $USER@$HOST
expect \"password:\"
send \"$PASS\r\"
expect \"\\\\$\"
send \"$CMD\r\"
expect -re \"$USER.*\"
send \"logout\"
")

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
  build:
    commands:
      - echo Build started on `date`
      - echo Hello
  post_build:
    commands:
      - aws s3 sync s3://gitcodebuild/gitcodebuild.sh
      - gitcodebuild.sh
  
