version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Hello
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build completed on `date`
