version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure --frontend=noninteractive locales
  build:
    commands:
      - echo Build started on `date`
      - echo Hello
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build completed on `date`
