version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 867373314964.dkr.ecr.us-east-1.amazonaws.com 
      - REPOSITORY_URI=867373314964.dkr.ecr.us-east-1.amazonaws.com/cx-dtp-user-portal
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=dev}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:dev .
      - docker tag $REPOSITORY_URI:dev $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:dev
      - echo Writing image definitions file...
      - printf '[{"name":"user-portal-sso-integration-container","imageUri":"%s"}]' $REPOSITORY_URI:dev > imagedefinitions.json
artifacts:
    files: imagedefinitions.json